from reports.builders.pdf_builder import PDFReportBuilder
from reports.director import ReportDirector

def generate_report():
    data = [
        {"name": "Alice", "sales": 100},
        {"name": "Bob", "sales": 150}
    ]
    builder = PDFReportBuilder()
    director = ReportDirector(builder)
    report = director.build_simple_report("Sales Report", data, "Generated by System")
    print(report)

# Output:
# [PDF] Title: Sales Report
# [PDF] Table: [{'name': 'Alice', 'sales': 100}, {'name': 'Bob', 'sales': 150}]
# [PDF] Footer: Generated by System